name: Run tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test-problem-definition:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checks with pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Test problem definition pre-built image
        run: |
          docker run --rm \
            -e EAGER_CONSTANT_FOLDING=TRUE \
            -v ${{ github.workspace }}:/workspace \
            johannahaffner/pycutest:latest \
            bash -c "cd /workspace && pip install -e . && pytest tests/test_problem.py"

  test-problem-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test problem runtime for problems A-M with pre-built image
        run: |
          docker run --rm \
            -e EAGER_CONSTANT_FOLDING=TRUE \
            -v ${{ github.workspace }}:/workspace \
            johannahaffner/pycutest:latest \
            bash -c "cd /workspace && pip install -e . && pytest tests/test_runtime.py --letters=A-M"

      - name: Test problem runtime for problems N-Z with pre-built image
        run: |
          docker run --rm \
            -e EAGER_CONSTANT_FOLDING=TRUE \
            -v ${{ github.workspace }}:/workspace \
            johannahaffner/pycutest:latest \
            bash -c "cd /workspace && pip install -e . && pytest tests/test_runtime.py --letters=N-Z"
